# Generated by Django 4.1.1 on 2023-05-04 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CusProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('phone_num', models.CharField(default='+8800000000', max_length=11)),
                ('credit_card_num', models.CharField(default='159753456', max_length=10)),
                ('address', models.CharField(default='Address', max_length=100)),
                ('city', models.CharField(default='City', max_length=20)),
                ('zip_code', models.CharField(default='0000', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
