# Generated by Django 4.1.1 on 2023-05-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dri_name', models.CharField(max_length=20)),
                ('dri_age', models.CharField(max_length=2)),
                ('dri_address', models.CharField(max_length=300)),
                ('dri_experience', models.CharField(max_length=50)),
                ('dri_lic_num', models.CharField(max_length=50)),
                ('accident_history', models.TextField(max_length=100)),
                ('expected_salary', models.CharField(max_length=15)),
                ('dri_img', models.ImageField(upload_to='media')),
                ('dri_phone_num', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Rental_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_num', models.CharField(max_length=20)),
                ('seating_capacity', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=15)),
                ('car_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Van', 'Van'), ('Micro', 'Micro')], max_length=20)),
                ('car_colour', models.CharField(max_length=10)),
                ('car_mileage', models.CharField(max_length=5)),
                ('car_model', models.CharField(max_length=50)),
                ('renter_name', models.CharField(max_length=50)),
                ('renter_phone_num', models.CharField(max_length=11)),
                ('rate_per_hour', models.CharField(max_length=10)),
                ('rate_per_day', models.CharField(max_length=10)),
                ('car_image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Selling_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Van', 'Van'), ('Micro', 'Micro'), ('Jeep', 'Jeep')], max_length=20)),
                ('price', models.CharField(max_length=15)),
                ('fuel_type', models.CharField(max_length=10)),
                ('eng_displacement', models.CharField(max_length=15)),
                ('eng_torque', models.CharField(max_length=50)),
                ('no_of_cylinder', models.IntegerField()),
                ('ground_clearance', models.CharField(max_length=10)),
                ('kerb_weight', models.CharField(max_length=10)),
                ('boot_space', models.CharField(max_length=10)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_address', models.CharField(max_length=300)),
                ('advance', models.CharField(max_length=300)),
                ('availability', models.CharField(max_length=20)),
                ('car_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
